import type { PageDef } from '@/shared/types/page';

export const adminPages: PageDef[] = [
  {
    path: 'admin/profile',
    title: 'School / College Profile & Branding',
    persona: 'ADMIN',
    permission: 'tenant.settings',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/ProfilePage'),
  },
  {
    path: 'admin/academic-year',
    title: 'Academic Year & Terms',
    persona: 'ADMIN',
    permission: 'tenant.settings',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/AcademicYearPage'),
  },
  {
    path: 'admin/dropdowns',
    title: 'Dynamic Dropdowns',
    persona: 'ADMIN',
    permission: 'tenant.settings',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/DropdownsPage'),
  },
  {
    path: 'admin/rooms',
    title: 'Rooms',
    persona: 'ADMIN',
    permission: 'tenant.settings',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/RoomsPage'),
  },
  {
    path: 'admin/templates',
    title: 'Document & Number Templates',
    persona: 'ADMIN',
    permission: 'tenant.settings',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/TemplatesPage'),
  },
  {
    path: 'admin/holiday-calendar',
    title: 'Holiday Calendar',
    persona: 'ADMIN',
    permission: 'tenant.settings',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/HolidayCalendarPage'),
  },
];
