import type { PageDef } from '@/shared/types/page';

export const academicsPages: PageDef[] = [
  {
    path: 'programs',
    title: 'Programs',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
    nav: true,
  },
  {
    path: 'programs/:id',
    title: 'Program Detail',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
  },
  {
    path: 'program-stages',
    title: 'Program Stages',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
    nav: true,
  },
  {
    path: 'program-stages/:id',
    title: 'Program Stage Detail',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
  },
  {
    path: 'subjects',
    title: 'Subjects',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
    nav: true,
  },
  {
    path: 'subjects/:id',
    title: 'Subject Detail',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
  },
  {
    path: 'curriculum',
    title: 'Curriculum',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
    nav: true,
  },
  {
    path: 'sections',
    title: 'Sections',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
    nav: true,
  },
  {
    path: 'sections/:id',
    title: 'Section Detail',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
  },
  {
    path: 'enrollment',
    title: 'Enrollment',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
    nav: true,
  },
  {
    path: 'teaching-assignments',
    title: 'Teaching Assignments',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T1',
    status: 'planned',
    nav: true,
  },
  {
    path: 'attendance',
    title: 'Attendance',
    persona: 'ADMIN',
    permission: 'attendance.mark',
    tier: 'T1',
    status: 'planned',
    nav: true,
  },
  {
    path: 'exams',
    title: 'Exams',
    persona: 'ADMIN',
    permission: 'exam.manage',
    tier: 'T2',
    status: 'planned',
    nav: true,
  },
  {
    path: 'exams/:id',
    title: 'Exam Detail',
    persona: 'ADMIN',
    permission: 'exam.manage',
    tier: 'T2',
    status: 'planned',
  },
  {
    path: 'marks',
    title: 'Marks Entry',
    persona: 'ADMIN',
    permission: 'marks.enter',
    tier: 'T2',
    status: 'planned',
    nav: true,
  },
  {
    path: 'timetable',
    title: 'Timetable',
    persona: 'ADMIN',
    permission: 'academics.manage',
    tier: 'T2',
    status: 'planned',
    nav: true,
  },
];
