import type { PageDef } from '@/shared/types/page';

export const financePages: PageDef[] = [
  {
    path: 'fee-heads',
    title: 'Fee Heads',
    persona: 'ADMIN',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/FeeHeadsPage'),
  },
  {
    path: 'fee-structures',
    title: 'Fee Structures',
    persona: 'ADMIN',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/FeeStructuresPage'),
  },
  {
    path: 'fee-structures/:id',
    title: 'Fee Structure Detail',
    persona: 'ADMIN',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    element: () => import('./pages/FeeStructureDetailPage'),
  },
  {
    path: 'fee-schedules',
    title: 'Fee Schedules',
    persona: 'ADMIN',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/FeeSchedulesPage'),
  },
  {
    path: 'invoices',
    title: 'Invoices',
    persona: 'ADMIN',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/InvoicesPage'),
  },
  {
    path: 'invoices/:id',
    title: 'Invoice Detail',
    persona: 'ADMIN',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    element: () => import('./pages/InvoiceDetailPage'),
  },
  {
    path: 'collection',
    title: 'Fee Collection Counter',
    persona: 'STAFF',
    permission: 'payment.record',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/CollectionPage'),
  },
  {
    path: 'concessions',
    title: 'Concessions & Scholarships',
    persona: 'ADMIN',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/ConcessionsPage'),
  },
  {
    path: 'fines',
    title: 'Fines',
    persona: 'ADMIN',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/FinesPage'),
  },
  {
    path: 'ledger',
    title: 'Student Ledger',
    persona: 'STAFF',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/LedgerIndexPage'),
  },
  {
    path: 'ledger/:studentId',
    title: 'Student Ledger Detail',
    persona: 'STAFF',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    element: () => import('./pages/StudentLedgerPage'),
  },
  {
    path: 'dues',
    title: 'Dues & Aging Reports',
    persona: 'ADMIN',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/DuesPage'),
  },
  {
    path: 'audit-trail',
    title: 'Financial Audit Trail',
    persona: 'ADMIN',
    permission: 'fee.manage',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/AuditTrailPage'),
  },
  {
    path: 'cash-close',
    title: 'Daily Cash Close',
    persona: 'STAFF',
    permission: 'payment.record',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/CashClosePage'),
  },
];
