import type { PageDef } from '@/shared/types/page';

export const guardiansPages: PageDef[] = [
  // Tier 1 — read-only portal (identity-scoped to own children via guardian_student)
  {
    path: 'guardian',
    title: 'Dashboard',
    persona: 'GUARDIAN',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/GuardianDashboard'),
  },
  {
    path: 'guardian/children/:childId/attendance',
    title: 'Child Attendance',
    persona: 'GUARDIAN',
    permission: 'guardian.read_child',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/ChildAttendancePage'),
  },
  {
    path: 'guardian/children/:childId/marks',
    title: 'Child Marks & Report Card',
    persona: 'GUARDIAN',
    permission: 'guardian.read_child',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/ChildMarksPage'),
  },
  {
    path: 'guardian/children/:childId/timetable',
    title: 'Child Timetable',
    persona: 'GUARDIAN',
    permission: 'guardian.read_child',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/ChildTimetablePage'),
  },
  {
    path: 'guardian/children/:childId/fees',
    title: 'Child Fees',
    persona: 'GUARDIAN',
    permission: 'guardian.read_fees',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/ChildFeesPage'),
  },
  {
    path: 'guardian/notices',
    title: 'Notices',
    persona: 'GUARDIAN',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/NoticesPage'),
  },
  // Tier 2 — guarded writes
  {
    path: 'guardian/children/:childId/fees/pay',
    title: 'Pay Fees Online',
    persona: 'GUARDIAN',
    permission: 'guardian.pay_fees',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/PayFeesPage'),
  },
  {
    path: 'guardian/notices/:noticeId/acknowledge',
    title: 'Consent & Acknowledge Notices',
    persona: 'GUARDIAN',
    tier: 'T2',
    status: 'done',
    element: () => import('./pages/NoticeAcknowledgePage'),
  },
  {
    path: 'guardian/contact',
    title: 'Update Own Contact',
    persona: 'GUARDIAN',
    permission: 'guardian.update_own_contact',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/ContactPage'),
  },
  {
    path: 'guardian/children/:childId/leave-request',
    title: 'Leave Request',
    persona: 'GUARDIAN',
    permission: 'guardian.request_leave',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/LeaveRequestPage'),
  },
];
