import type { PageDef } from '@/shared/types/page';

export const studentsPages: PageDef[] = [
  // --- ADMIN / STAFF: People → Students management ---
  {
    path: 'students',
    title: 'Students',
    persona: 'ADMIN',
    permission: 'student.read',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/StudentsRosterPage'),
  },
  {
    path: 'students/onboard',
    title: 'Onboard student',
    persona: 'ADMIN',
    permission: 'student.onboard',
    tier: 'T1',
    status: 'done',
    element: () => import('./pages/OnboardStudentPage'),
  },
  {
    path: 'students/:id',
    title: 'Student detail',
    persona: 'ADMIN',
    permission: 'student.read',
    tier: 'T1',
    status: 'done',
    element: () => import('./pages/StudentDetailPage'),
  },
  {
    path: 'students/import',
    title: 'Bulk import students',
    persona: 'ADMIN',
    permission: 'student.create',
    tier: 'T1',
    status: 'done',
    element: () => import('./pages/ImportStudentsPage'),
  },

  // --- ADMIN / STAFF: Guardian record management ---
  {
    path: 'guardians',
    title: 'Guardians',
    persona: 'ADMIN',
    permission: 'student.read',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/GuardiansPage'),
  },
  {
    path: 'guardians/:id',
    title: 'Guardian detail',
    persona: 'ADMIN',
    permission: 'student.update',
    tier: 'T1',
    status: 'done',
    element: () => import('./pages/GuardianDetailPage'),
  },

  // --- STUDENT: self-service portal (identity-scoped, no permission gate) ---
  {
    path: 'student',
    title: 'Dashboard',
    persona: 'STUDENT',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/portal/StudentDashboardPage'),
  },
  {
    path: 'student/profile',
    title: 'My profile',
    persona: 'STUDENT',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/portal/StudentProfilePage'),
  },
  {
    path: 'student/attendance',
    title: 'My attendance',
    persona: 'STUDENT',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/portal/StudentAttendancePage'),
  },
  {
    path: 'student/marks',
    title: 'My marks / report card',
    persona: 'STUDENT',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/portal/StudentMarksPage'),
  },
  {
    path: 'student/timetable',
    title: 'My timetable',
    persona: 'STUDENT',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/portal/StudentTimetablePage'),
  },
  {
    path: 'student/fees',
    title: 'My fees / dues',
    persona: 'STUDENT',
    tier: 'T1',
    status: 'done',
    nav: true,
    element: () => import('./pages/portal/StudentFeesPage'),
  },
  {
    path: 'student/notices',
    title: 'Notices',
    persona: 'STUDENT',
    tier: 'T2',
    status: 'done',
    nav: true,
    element: () => import('./pages/portal/StudentNoticesPage'),
  },
];
